#Step 1
FROM ubuntu:16.04

#Step 1a–install Ubuntu packages needed for installing SQL Server
RUN apt-get update && apt-get install -y curl apt-utils apt-transport-https software-properties-common

#Step 1b-download and install public GPG keys for SQL Server
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

#Step 2
RUN add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main"
RUN apt-get update

#Step 3
RUN apt-get install -y mssql-server

#Modified Line 11
RUN mkdir -p -m 770 /var/opt/mssql && chown -R mssql:0 /var/opt/mssql && chgrp -R 0 /var/opt/mssql

#Lines 15, 19, and 20
RUN setcap 'cap_net_bind_service+ep' /opt/mssql/bin/sqlservr
RUN setcap 'cap_sys_ptrace+ep' /opt/mssql/bin/paldumper
RUN setcap 'cap_sys_ptrace+ep' /usr/bin/gdb

#Lines 25, 26, and 27
RUN mkdir -p /etc/ld.so.conf.d && touch /etc/ld.so.conf.d/mssql.conf
RUN echo -e "# mssql libs\n/opt/mssql/lib" >> /etc/ld.so.conf.d/mssql.conf
RUN ldconfig

#Tell user what port this container will use
EXPOSE 1433

#Line 29
USER mssql

#Step 5
ENV PATH=${PATH}:/opt/mssql/bin

#Step 6
CMD sqlservr
