version: "3"
services:
wfe:
   build: ./mssql-aspcore-example-app
   ports:
     - "8080:5000"
   depends_on:
     - db

db:
   build: ./mssql-aspcore-example-db
   environment:
     SA_PASSWORD: "mYSecUr3PAssw0rd"
     ACCEPT_EULA: "Y"
   ports:
     - "1500:1433"